"""
Data export and synthetic data generation module for the Italian Real Estate pipeline.

This module provides functionality for:
1. Exporting real data from PostgreSQL to Parquet format
2. Generating synthetic real estate listings using K-Nearest Neighbors (KNN) interpolation

The synthetic data generation approach works as follows:
1. For each listing type (rent, auction, sale), a seed listing is randomly selected
2. The K nearest neighbors are found based on price, location, and surface
3. A new synthetic listing is generated by interpolating features:
   - Numerical features: weighted average (weights inversely proportional to distance)
   - Categorical features: most frequent value among neighbors

Submodules:
    data_extractor: PostgreSQL data extraction queries
    preprocessor: Data cleaning and normalization
    knn_generator: TensorFlow GPU-accelerated KNN synthetic generation
    gpu_utils: GPU memory management utilities
    postprocessor: Rounding and cleanup of generated data
    real_data_exporter: Real data export to Parquet with preprocessing

Author: Leonardo Pacciani-Mori
License: MIT
"""

from .data_extractor import (
    extract_data_from_postgres,
    extract_features_from_postgres,
    merge_features_with_data,
)
from .preprocessor import (
    preprocess_data,
    one_hot_encode_in_place,
    split_by_listing_type,
)
from .knn_generator import (
    process_dataset,
    generate_synthetic_data,
    generate_synthetic_data_in_chunks,
)
from .gpu_utils import configure_gpu_memory_growth, clear_gpu_memory, get_gpu_info
from .postprocessor import (
    postprocess_synthetic_data,
    random_round,
    combine_synthetic_data,
)
from .real_data_exporter import (
    export_real_data,
    get_listing_counts,
    get_rounded_listing_counts,
    round_to_myriad,
)

__all__ = [
    # Data extraction
    "extract_data_from_postgres",
    "extract_features_from_postgres",
    "merge_features_with_data",
    # Preprocessing
    "preprocess_data",
    "one_hot_encode_in_place",
    "split_by_listing_type",
    # KNN generation
    "process_dataset",
    "generate_synthetic_data",
    "generate_synthetic_data_in_chunks",
    # GPU utilities
    "configure_gpu_memory_growth",
    "clear_gpu_memory",
    "get_gpu_info",
    # Postprocessing
    "postprocess_synthetic_data",
    "random_round",
    "combine_synthetic_data",
    # Real data export
    "export_real_data",
    "get_listing_counts",
    "get_rounded_listing_counts",
    "round_to_myriad",
]
